language: "python"

sudo: required

services:
   - postgresql

env:
   - PGVERSION=9.5
   - PGVERSION=9.6

before_script:
   - pip install psycopg2

script:
   - python ./pg-info.py

notifications:
  email:
    on_success: change
    on_failure: always
